# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

[tool.poetry]
name = "os2mo-sdtool-plus"
version = "0.0.0" # versioning handled by conventional commits
description = "Synchronises MO with SD Løn"
authors = ["Magenta ApS <info@magenta.dk>"]
readme = "README.md"
homepage = "https://magenta.dk/"
repository = "https://git.magenta.dk/rammearkitektur/os2mo-sdtool-plus"
keywords = ["os2mo", "sd"]
license = "MPL-2.0"

[tool.poetry.dependencies]
# TODO: add ruff - https://docs.astral.sh/ruff/rules/#pydocstyle-d
ariadne-codegen = {extras = ["subscriptions"], version = "^0.7.1"}
python = "^3.11"
click = "^8"
gql = "^3"
deepdiff = "^6"
anytree = "^2"
pydantic = "^1"
more-itertools = "^9"
hypothesis = "^6"
another-sd-client = "^1"
prometheus-fastapi-instrumentator = "^6"
uvicorn = "^0.23"
sentry-sdk = "^1"
structlog = "^23"
fastramqpi = "7"
freezegun = "^1"
alembic = "^1"
psycopg2 = "^2"
os2mo-dar-client = "^1"
email-validator = "^2"

[tool.ariadne-codegen]
target_package_name = "autogenerated_graphql_client"
target_package_path = "sdtoolplus/"
client_name = "GraphQLClient"
schema_path = "schema.graphql"  # curl -O http://localhost:5000/graphql/v7/schema.graphql
queries_path = "queries.graphql"
plugins = [
    # Return values directly when only a single top field is requested
    "ariadne_codegen.contrib.shorter_results.ShorterResultsPlugin",
]
[tool.ariadne-codegen.scalars.DateTime]
type = "datetime.datetime"
[tool.ariadne-codegen.scalars.UUID]
type = "uuid.UUID"

[tool.poetry.group.dev.dependencies]
aiohttp = "^3"
types-python-dateutil = "^2"

[tool.poetry.group.test.dependencies]
pre-commit = "^3"
pytest = "^7"
pytest-cov = "^4"
pytest-split = "^0.8"
pytest-asyncio = "^0.23"

[tool.pytest.ini_options]
asyncio_mode="auto"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
