# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
from datetime import datetime
from uuid import uuid4, UUID
from zoneinfo import ZoneInfo

import pytest
from httpx import AsyncClient
from respx import MockRouter

from sdtoolplus.autogenerated_graphql_client import TestingCreateOrgUnitOrgUnitCreate, \
    EngagementCreateInput, RAValidityInput, EmployeeCreateInput, EngagementUpdateInput
from sdtoolplus.depends import GraphQLClient


@pytest.mark.integration_test
async def test_ou_timeline_name_http_triggered_sync(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,  # Maybe switch
    base_tree_builder: TestingCreateOrgUnitOrgUnitCreate,
    engagement_type: UUID,
    job_function_1234: UUID,
    job_function_5678: UUID,
    job_function_9000: UUID,
    respx_mock: MockRouter,
):
    """
    This is it. If this test passes, all of our worries will be over, and we will never
    ever have to touch the SD engagement sync code again :-)

    We are testing this scenario:

    Time  --------t1--------t2---------t3------t4-----t5-----t6------------t7------->

    MO (name)               |------name4-------|---------------name5-----------------
    MO (key)                |------------- 1234 -------------|-------- 5678 ---------
    MO (unit)               |---dep3----|-------------------dep4---------------------
    MO (ext_7)              |----v1-----|--v2--|--v3--|--v4--|--------v5-------------
    MO (active)             |--------------------------------------------------------

    "Arrange" intervals     |-----1----|---2---|---3--|---4--|---------5-------------

    SD (name)     |-------name1--------|----name2-----|-------name3------------------
    SD (key)      |------------------------ 9000 ------------------------------------
    SD (unit)     |---dep1--|-------------------dep2---------------------------------
    SD (active)   |---------1----------|-------3------|---8--|-------1-----|

    "Assert"      |----1----|-----2----|---3---|--4---|--5---|-----6-------|----7----
    intervals

    In SD: name = EmploymentName, key = JobPositionIdentifier
           active = EmploymentStatusCode
    In MO: name = extension_1, key = user_key
    """
    # Arrange
    tz = ZoneInfo("Europe/Copenhagen")

    t1 = datetime(2001, 1, 1, tzinfo=tz)
    t2 = datetime(2002, 1, 1, tzinfo=tz)
    t3 = datetime(2003, 1, 1, tzinfo=tz)
    t4 = datetime(2004, 1, 1, tzinfo=tz)
    t5 = datetime(2005, 1, 1, tzinfo=tz)
    t6 = datetime(2006, 1, 1, tzinfo=tz)
    t7 = datetime(2007, 1, 1, tzinfo=tz)

    # Create person
    person_uuid = uuid4()
    await graphql_client._testing__create_person(
        EmployeeCreateInput(
            uuid=person_uuid,
            cpr="0101011234",
            given_name="Bruce",
            surname="Lee",
        )
    )

    # Create engagement (arrange intervals 1-5)
    eng_uuid = (
        await graphql_client.create_engagement(
            EngagementCreateInput(
                user_key="II-54321",
                validity=RAValidityInput(
                    from_=t2,
                    to=None
                ),
                extension_1="name4",
                extension_7="v1",
                person=person_uuid,
                org_unit=UUID("30000000-0000-0000-0000-000000000000"),  # dep3
                engagement_type=engagement_type,
                job_function=job_function_1234
            )
        )
    ).uuid

    # Update engagement (arrange interval 2)
    await graphql_client.update_engagement(
        EngagementUpdateInput(
            uuid=eng_uuid,
            user_key="II-54321",
            validity=RAValidityInput(
                from_=t3,
                to=t4
            ),
            extension_1="name4",
            extension_7="v2",
            person=person_uuid,
            org_unit=UUID("40000000-0000-0000-0000-000000000000"),
            engagement_type=engagement_type,
            job_function=job_function_1234
        )
    )

    # Update engagement (arrange interval 3)
    await graphql_client.update_engagement(
        EngagementUpdateInput(
            uuid=eng_uuid,
            user_key="II-54321",
            validity=RAValidityInput(
                from_=t4,
                to=t5
            ),
            extension_1="name5",
            extension_7="v3",
            person=person_uuid,
            org_unit=UUID("40000000-0000-0000-0000-000000000000"),
            engagement_type=engagement_type,
            job_function=job_function_1234
        )
    )

    # Update engagement (arrange interval 4)
    await graphql_client.update_engagement(
        EngagementUpdateInput(
            uuid=eng_uuid,
            user_key="II-54321",
            validity=RAValidityInput(
                from_=t5,
                to=t6
            ),
            extension_1="name5",
            extension_7="v4",
            person=person_uuid,
            org_unit=UUID("40000000-0000-0000-0000-000000000000"),
            engagement_type=engagement_type,
            job_function=job_function_1234
        )
    )

    # Update engagement (arrange interval 5)
    await graphql_client.update_engagement(
        EngagementUpdateInput(
            uuid=eng_uuid,
            user_key="II-54321",
            validity=RAValidityInput(
                from_=t6,
                to=None
            ),
            extension_1="name5",
            extension_7="v5",
            person=person_uuid,
            org_unit=UUID("40000000-0000-0000-0000-000000000000"),
            engagement_type=engagement_type,
            job_function=job_function_5678
        )
    )

    sd_resp = f"""<?xml version="1.0" encoding="UTF-8"?>
        <GetEmploymentChanged20111201 creationDateTime="2025-03-10T13:50:06">
          <RequestStructure>
            <InstitutionIdentifier>II</InstitutionIdentifier>
            <PersonCivilRegistrationIdentifier>0101011234</PersonCivilRegistrationIdentifier>
            <ActivationDate>2001-01-01</ActivationDate>
            <DeactivationDate>2006-12-31</DeactivationDate>
            <DepartmentIndicator>true</DepartmentIndicator>
            <EmploymentStatusIndicator>true</EmploymentStatusIndicator>
            <ProfessionIndicator>true</ProfessionIndicator>
            <SalaryAgreementIndicator>false</SalaryAgreementIndicator>
            <SalaryCodeGroupIndicator>false</SalaryCodeGroupIndicator>
            <WorkingTimeIndicator>false</WorkingTimeIndicator>
            <UUIDIndicator>true</UUIDIndicator>
          </RequestStructure>
          <Person>
            <PersonCivilRegistrationIdentifier>0101011234</PersonCivilRegistrationIdentifier>
            <Employment>
              <EmploymentIdentifier>54321</EmploymentIdentifier>
              <EmploymentDate>2001-01-01</EmploymentDate>
              <AnniversaryDate>2001-01-01</AnniversaryDate>
              <EmploymentDepartment>
                <ActivationDate>2001-01-01</ActivationDate>
                <DeactivationDate>2001-12-31</DeactivationDate>
                <DepartmentIdentifier>dep1</DepartmentIdentifier>
                <DepartmentUUIDIdentifier>10000000-0000-0000-0000-000000000000</DepartmentUUIDIdentifier>
              </EmploymentDepartment>
              <EmploymentDepartment>
                <ActivationDate>2002-01-01</ActivationDate>
                <DeactivationDate>9999-12-31</DeactivationDate>
                <DepartmentIdentifier>dep2</DepartmentIdentifier>
                <DepartmentUUIDIdentifier>20000000-0000-0000-0000-000000000000</DepartmentUUIDIdentifier>
              </EmploymentDepartment>
              <Profession>
                <ActivationDate>2001-01-01</ActivationDate>
                <DeactivationDate>2002-12-31</DeactivationDate>
                <JobPositionIdentifier>9000</JobPositionIdentifier>
                <EmploymentName>name1</EmploymentName>
                <AppointmentCode>0</AppointmentCode>
              </Profession>
              <Profession>
                <ActivationDate>2003-01-01</ActivationDate>
                <DeactivationDate>2004-12-31</DeactivationDate>
                <JobPositionIdentifier>9000</JobPositionIdentifier>
                <EmploymentName>name2</EmploymentName>
                <AppointmentCode>0</AppointmentCode>
              </Profession>
              <Profession>
                <ActivationDate>2005-01-01</ActivationDate>
                <DeactivationDate>9999-12-31</DeactivationDate>
                <JobPositionIdentifier>9000</JobPositionIdentifier>
                <EmploymentName>name3</EmploymentName>
                <AppointmentCode>0</AppointmentCode>
              </Profession>
              <EmploymentStatus>
                <ActivationDate>2001-01-01</ActivationDate>
                <DeactivationDate>2002-12-31</DeactivationDate>
                <EmploymentStatusCode>1</EmploymentStatusCode>
              </EmploymentStatus>
              <EmploymentStatus>
                <ActivationDate>2003-01-01</ActivationDate>
                <DeactivationDate>2004-12-31</DeactivationDate>
                <EmploymentStatusCode>3</EmploymentStatusCode>
              </EmploymentStatus>
              <EmploymentStatus>
                <ActivationDate>2005-01-01</ActivationDate>
                <DeactivationDate>2005-12-31</DeactivationDate>
                <EmploymentStatusCode>8</EmploymentStatusCode>
              </EmploymentStatus>
              <EmploymentStatus>
                <ActivationDate>2006-01-01</ActivationDate>
                <DeactivationDate>2006-12-31</DeactivationDate>
                <EmploymentStatusCode>1</EmploymentStatusCode>
              </EmploymentStatus>
              <EmploymentStatus>
                <ActivationDate>2007-01-01</ActivationDate>
                <DeactivationDate>9999-12-31</DeactivationDate>
                <EmploymentStatusCode>8</EmploymentStatusCode>
              </EmploymentStatus>
            </Employment>
          </Person>
        </GetEmploymentChanged20111201>
    """

    # Act
    r = await test_client.post(
        "/timeline/sync/engagement", params={
            "inst_id": "II",
        }
    )