# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
root_organisation:
  municipality_code: null

facets:
  org_unit_type:
    Enhed:
      title: "Enhed"
      scope: "TEXT"
  org_unit_level:
    Afdelings-niveau:
      title: "Afdelings-niveau"
      scope: "TEXT"
    NY0-niveau:
      title: "NY0-niveau"
      scope: "TEXT"
    NY1-niveau:
      title: "NY1-niveau"
      scope: "TEXT"
    NY2-niveau:
      title: "NY2-niveau"
      scope: "TEXT"
    NY3-niveau:
      title: "NY3-niveau"
      scope: "TEXT"
    NY4-niveau:
      title: "NY4-niveau"
      scope: "TEXT"
    non-SD:
      title: "non-SD"
      scope: "TEXT"
  org_unit_hierarchy:
    linjeorg:
      title: "Linjeorganisation"
      scope: "TEXT"
  visibility:
    Intern:
      title: "Må vises internt"
      scope: "INTERNAL"
  org_unit_address_type:
    Pnummer:
      title: "P-nummer"
      scope: "PNUMBER"
    AddressMailUnit:
      title: "Postadresse"
      scope: "DAR"
    AdresseAPOSOrgUnit:
      title: "Postadresse fra SD"
      scope: "TEXT"
    lokation_telefon_lokal:
      title: "Telefon lokal"
      scope: "PHONE"
    P-nummer:
      title: "P-nummer"
      scope: "PNUMBER"
  engagement_type:
    TestAnsat:
      title: "TestAnsat"
      scope: "TEXT"
    SDbe3edd69-16c1-4dcb-a8c1-16b4db611b9b:
      title: "Månedslønnet, fuldtid"
      scope: "TEXT"
    SD609dc578-65cc-47b3-8811-ffd1cad5b981:
      title: "Månedslønnet, deltid"
      scope: "TEXT"
    SD266921e5-c58b-4ded-92c5-61b30ba9bfb0:
      title: "Timelønnet"
      scope: "TEXT"
  engagement_job_function:
    Ninja:
      title: "Ninja"
      scope: "0"
    1234:
      title: "Kung Fu Master"
      scope: "0"
    5678:
      title: "Shogun"
      scope: "0"
    9000:
      title: "Karate Coach"
      scope: "0"
  leave_type:
    Orlov:
      title: "Orlov"
      scope: "TEXT"
