# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
from datetime import datetime

import structlog

from sdtoolplus.autogenerated_graphql_client import OrganisationUnitTerminateInput
from sdtoolplus.autogenerated_graphql_client import OrganisationUnitUpdateInput
from sdtoolplus.autogenerated_graphql_client import RAValidityInput
from sdtoolplus.depends import GraphQLClient
from sdtoolplus.mo_org_unit_importer import OrgUnitUUID
from sdtoolplus.models import Active
from sdtoolplus.models import T
from sdtoolplus.models import Timeline
from sdtoolplus.models import UnitName
from sdtoolplus.models import UnitTimeline
from sdtoolplus.sd.tree import ASSUMED_SD_TIMEZONE

logger = structlog.get_logger()


def _get_mo_validity(interval: T) -> RAValidityInput:
    mo_end: datetime | None = interval.end
    assert mo_end is not None
    if mo_end.replace(tzinfo=None) == datetime.max:
        mo_end = None
    return RAValidityInput(from_=interval.start, to=mo_end)


async def update_ou_name(
    gql_client: GraphQLClient,
    org_unit: OrgUnitUUID,
    diff_timeline: Timeline[UnitName],
) -> None:
    for unit_name in diff_timeline.intervals:
        await gql_client.update_org_unit(
            OrganisationUnitUpdateInput(
                uuid=org_unit,
                name=unit_name.value,
                validity=_get_mo_validity(unit_name),
            )
        )


def _get_termination_intervals(
    diff_timeline: Timeline[Active]
) -> tuple[Active, ...]:
    full_inactive_timeline = Timeline[Active](
        intervals=(
            Active(
                start=datetime.min.replace(tzinfo=ASSUMED_SD_TIMEZONE),
                end=datetime.max.replace(tzinfo=ASSUMED_SD_TIMEZONE),
                value=False
            ),
        )
    )
    active_timeline = Timeline[Active](
        intervals=tuple(
            Active(
                start=active.start,
                end=active.end,
                value=True,
            )
            for active in diff_timeline.intervals
            # This will get rid of the "None" values
            if active.value is True
        )
    )
    term_timeline = full_inactive_timeline.diff(active_timeline)

    return term_timeline.intervals


async def terminate_ou(
    gql_client: GraphQLClient,
    org_unit: OrgUnitUUID,
    diff_timeline: Timeline[Active],
) -> None:
    logger.info("(Re-)terminate OU", org_unit=str(org_unit))

    termination_intervals = tuple(
        active for active in diff_timeline.intervals if active.value is None
    )
    logger.debug("Termination intervals", intervals=termination_intervals)

    for active in termination_intervals:
        mo_validity = _get_mo_validity(active)
        await gql_client.terminate_org_unit(
            OrganisationUnitTerminateInput(
                uuid=org_unit,
                from_=mo_validity.from_,
                to=mo_validity.to,
            )
        )


async def update_ou(
    gql_client: GraphQLClient,
    org_unit: OrgUnitUUID,
    sd_unit_timeline: UnitTimeline,
    mo_unit_timeline: UnitTimeline,
    dry_run: bool,
) -> None:
    logger.info("Update OU in MO", org_unit=str(org_unit))

    diff = UnitTimeline(
        active=sd_unit_timeline.active.diff(mo_unit_timeline.active),
        name=sd_unit_timeline.name.diff(mo_unit_timeline.name),
    )
    logger.debug("UnitTimeline diff", diff=diff)

    await update_ou_name(gql_client, org_unit, diff.name)
    await terminate_ou(gql_client, org_unit, diff.active)
